import {
  BoxProps,
  CColor,
  CGradient,
  CRadius,
  CSize,
  ElementProps,
  PolymorphicFactory,
  StylesApiProps,
} from '../../core'
import AvatarGroup from './avatar-group/avatar-group.vue'

export type AvatarStylesNames = 'root' | 'placeholder' | 'image'
export type AvatarVariant =
  | 'default'
  | 'filled'
  | 'light'
  | 'gradient'
  | 'outline'
  | 'dashed'
  | 'transparent'
  | 'white'

export type AvatarCssVariables = {
  root: '--avatar-size' | '--avatar-radius' | '--avatar-bg' | '--avatar-color' | '--avatar-bd'
}

export interface AvatarProps extends BoxProps, StylesApiProps<AvatarFactory> {
  /**
   * Width and height of the avatar, numbers are converted to rem
   * @default 'md'
   */
  size?: CSize | (string | {}) | number

  /**
   * Key of `theme.radius` or any valid CSS value to set border-radius
   * @default '1000px'
   */
  radius?: CRadius

  /**
   * Key of `theme.colors` or any valid CSS color
   * @default 'gray'
   */
  color?: CColor | 'initials'

  /**
   * Gradient configuration for `variant="gradient"`
   * @default theme.defaultGradient
   */
  gradient?: CGradient

  /** Image url, if the image connot be loaded, then placeholder is displayed instead */
  src?: string

  /** Image `alt` attribute, also used as `title` attribute for placeholder */
  alt?: string

  /** Attributes passed down to `img` element */
  imageProps?: ElementProps<'img'>

  /** If set, adjusts text color based on background color for `filled` variant */
  autoContrast?: boolean

  /** Name of the user. When `src` is not set, used to display initials and to generate color when `color="initials"` is set. */
  name?: string

  /** A list of colors that is used for autogenerated initials. By default, all default CCK UI colors can be used except gray and dark */
  allowedInitialsColors?: CColor[]
}

export type AvatarFactory = PolymorphicFactory<{
  props: AvatarProps
  defaultRef: HTMLDivElement
  defaultComponent: 'div'
  stylesNames: AvatarStylesNames
  vars: AvatarCssVariables
  variant: AvatarVariant
  staticComponents: {
    Group: typeof AvatarGroup
  }
}>
